### ISSUE TITLE
Docs translation

### ISSUE THREAD

**Issue by joaochris** [mtdvlpr/meeting-media-manager#50]
Hi! From what I've seen the topics part is not translated.

![image](https://user-images.githubusercontent.com/76891864/198881751-23954fd4-38f6-42f6-baf3-08ead04916d8.png)
![image](https://user-images.githubusercontent.com/76891864/198881771-204a3f55-7d0d-4685-ba6a-78507d300661.png)

**Comment by mtdvlpr** [comment]
Correct. This is because there is some manual labor involved. I can't directly use your navigation translations, so once in a while, I have to manually copy paste your translations for the navigation to the place where they are defined. Working on it as we speak :)

**Comment by mtdvlpr** [comment]
Fixed in https://github.com/sircharlo/meeting-media-manager/pull/555

**Comment by mtdvlpr** [comment]
Look now :)

**Comment by mtdvlpr** [comment]
Small thing I noticed. You translated some blocks that are not meant to be translated. Block statements should be left as is, so `[GH ISSUES]` and `[PRESENT LINK]` for example.
![Screenshot from 2022-10-30 15-40-21](https://user-images.githubusercontent.com/46671786/198884688-cecc604a-e155-41f9-afce-511c536c6a21.png)

**Comment by joaochris** [comment]
Thanks! I will correct hahaha

**Comment by e-Feitosa** [comment]
@joaochris , alguns tem questionado essa questão do plugin, nessa nova versão já está OK, aceita o plugin v5. Sei que depende do arquivo em ingles para traduzir, há algo que possa fazer para atualizar essa informação dos documentos?

Local da informação
https://sircharlo.github.io/meeting-media-manager/pt-BR/#present-media
**Configuração inicial: OBS Studio**
![image](https://user-images.githubusercontent.com/90984283/203871124-d5ea70b8-3050-401d-8949-3d5d06b37829.png)

**Comment by mtdvlpr** [comment]
Hi @e-Feitosa, that is old information that managed to slip through. I have fixed it and it will be gone shortly :)

**Comment by e-Feitosa** [comment]
Hi @mtdvlpr, Maybe this sentence "Install the obs-websocket plugin" can be adjusted, the V5 plugin is already native in OBS Studio V28+

**Comment by mtdvlpr** [comment]
You are correct! Will do so :)

**Comment by mtdvlpr** [comment]
@e-Feitosa, I have updated the English strings, now it's up to the translators to renew their translations.

**Comment by joaochris** [comment]
@e-Feitosa If you have time, you can stick with the document translation part. As you said, this part needs to be updated, and a few other words.

**Comment by joaochris** [comment]
@mtdvlpr 
![image](https://user-images.githubusercontent.com/76891864/209445305-7fcf7cec-ae56-476a-a7e2-c2a5cc6ed818.png)
Can those parts with red squares be translated? I can only see the one I marked with the arrow.

**Comment by mtdvlpr** [comment]
They should be at the top of each page respectively

**Comment by joaochris** [comment]
> They should be at the top of each page respectively. It's the tag at the top of each file to be translated

Got it. Do they take time to show up?

**Comment by mtdvlpr** [comment]
Yes, after you've made a pr and that pr is merged here, I have to make a PR to merge it at Sircharlo's repo. Then it takes a few minutes to upload the changes to the docs site

**Comment by mtdvlpr** [comment]
Besides that, I have to fix some bugs from gitlocalize. Gitlocalize breaks some links. I will fix it when I'm back home.

**Comment by joaochris** [comment]
Got it. Thanks bro 😄🤝

**Comment by mtdvlpr** [comment]
To check if thr nav is correct, see: 
https://mtdvlpr.github.io/meeting-media-manager/pt-BR/

**Comment by joaochris** [comment]
@mtdvlpr small bug. 
![Screenshot_1](https://user-images.githubusercontent.com/76891864/211804639-1be47cf6-58a2-4197-a168-c2604a95fcbb.png)

**Comment by mtdvlpr** [comment]
It seems there was a new line in your translations. Fixed it for you :)
